# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-builtin-literals
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: trailing-whitespace
      - id: flake8
        args:
          - --statistics
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.1
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: rst-backticks
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: 37777b8097c5bd989464927bd8001de757795d56
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.2
    hooks:
      - id: seed-isort-config
        args:
          - --application-directories
          - barrier
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies:
          - isort[pyproject]
  - repo: https://github.com/ambv/black
    rev: e66451761fab864cce9077a3ee72999543b8ef65
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args:
          - -v
          - -c
          - bandit.yml
        exclude: ^.*(tests)/.*\.py$
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 4.0.0
    hooks:
      - id: pydocstyle
        verbose: true
        args:
          - --convention=numpy
          - --add-ignore=D100,D104,D105,D202
          - -e
