version: 2.1

executors:
  python:
    docker:
      - image: circleci/python@sha256:adb03470e8d7f869ac999b8ac7d0be8c426c73dfdc085e45e45d561815aa02f5
    working_directory: /home/circleci/g
    environment:
      PATH: /home/circleci/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


commands:
  check-code-quality:
    steps:
      - run:
          name: Install pre-commit
          command: pip install --user pre-commit==1.18.0
      - run:
          name: Run repository pre-commit hooks
          command: pre-commit run --all-files
  install-python-dependencies:
    parameters:
      no-dev:
        default: false
        type: boolean
    steps:
      - run:
          name: Install Python Dependencies
          command: poetry install <<# parameters.no-dev >>--no-dev<</ parameters.no-dev >>
  run-tests:
    steps:
      - run:
          name: Run py.test
          command: poetry run py.test
  build-docker-container:
    steps:
      - setup_remote_docker
      - run:
          name: Build Docker Container
          command: docker build .
  build-wheel:
    steps:
      - run:
          name: Build wheel
          command: poetry build


jobs:
  build-dist:
    executor: python
    steps:
      - checkout
      - install-python-dependencies:
          no-dev: true
      - build-wheel
      - build-docker-container
  run-tests:
    executor: python
    steps:
      - checkout
      - install-python-dependencies
      - run-tests
  check-code-quality:
    executor: python
    steps:
      - checkout
      - check-code-quality


workflows:
  version: 2
  build-and-test:
    jobs:
      - build-dist
      - run-tests
      - check-code-quality
